name: Scheduled Visual Component Tests
on: workflow_dispatch
#schedule:
# Runs at 12:00am UTC every day (see https://crontab.guru)
# - cron: '0 0 * * *'

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.0-noble
      options: --init --ipc=host --user pwuser

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm run pnpm:setup
      - name: Install dependencies
        run: pnpm ci
      - name: Run visual tests
        run: pnpm test:visual
      # if we want to upload the tests results however this can be large and therefore cost m
      # - name: Upload test results
      #   uses: actions/upload-artifact@v4
      #   if: failure()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 3
